version: '3'
services:
  httpser:
    build:
      context: ./
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ${HOME}/.httpser/:/httpser
      - /var/log/nginx/:/var/log/nginx/
